-- Hebrew–Arabic dictionary: initial PostgreSQL schema (v1).
-- Safe to run again: CREATE IF NOT EXISTS and ON CONFLICT DO NOTHING.
-- Demo entries are original hand-written samples, NOT imports from Kaikki/Curras.
BEGIN;

CREATE TABLE IF NOT EXISTS dictionary_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  homepage TEXT,
  license_id TEXT,
  license_url TEXT,
  attribution TEXT,
  imported_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS dictionary_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_key TEXT NOT NULL UNIQUE,
  hebrew TEXT NOT NULL,
  hebrew_search TEXT NOT NULL,
  part_of_speech TEXT,
  notes TEXT,
  review_status TEXT NOT NULL DEFAULT 'unreviewed'
    CHECK (review_status IN ('sample','unreviewed','reviewed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS arabic_forms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id BIGINT NOT NULL REFERENCES dictionary_entries(id) ON DELETE CASCADE,
  dialect TEXT NOT NULL CHECK (dialect IN ('msa','palestinian')),
  arabic_vocalized TEXT NOT NULL,
  arabic_search TEXT NOT NULL,
  hebrew_transliteration TEXT,
  notes TEXT,
  UNIQUE (entry_id, dialect, arabic_vocalized)
);

CREATE TABLE IF NOT EXISTS entry_sources (
  entry_id BIGINT NOT NULL REFERENCES dictionary_entries(id) ON DELETE CASCADE,
  source_id BIGINT NOT NULL REFERENCES dictionary_sources(id) ON DELETE RESTRICT,
  source_entry_url TEXT,
  source_record_id TEXT,
  change_notes TEXT,
  PRIMARY KEY (entry_id, source_id)
);

CREATE INDEX IF NOT EXISTS dictionary_entries_hebrew_search_idx
  ON dictionary_entries (hebrew_search);
CREATE INDEX IF NOT EXISTS arabic_forms_arabic_search_idx
  ON arabic_forms (arabic_search);
CREATE INDEX IF NOT EXISTS arabic_forms_entry_dialect_idx
  ON arabic_forms (entry_id, dialect);

INSERT INTO dictionary_sources (code,title,license_id,attribution)
VALUES ('manual-demo','Original demonstration entries','original-sample','Original example data for this prototype')
ON CONFLICT (code) DO NOTHING;

INSERT INTO dictionary_entries (entry_key,hebrew,hebrew_search,review_status)
VALUES
 ('he-shalom','שלום','שלום','sample'),
 ('he-bayit','בית','בית','sample'),
 ('he-mayim','מים','מים','sample'),
 ('he-ani-rotze','אני רוצה','אני רוצה','sample')
ON CONFLICT (entry_key) DO NOTHING;

INSERT INTO arabic_forms (entry_id,dialect,arabic_vocalized,arabic_search,hebrew_transliteration)
SELECT e.id,v.dialect,v.vocalized,v.search,v.transliteration
FROM (VALUES
 ('he-shalom','msa','سَلَام','سلام','סַלַאם'),
 ('he-shalom','palestinian','سَلَام','سلام','סַלַאם'),
 ('he-bayit','msa','بَيْت','بيت','בַּיְת'),
 ('he-bayit','palestinian','بَيْت','بيت','בֵּית'),
 ('he-mayim','msa','مَاء','ماء','מַאא׳'),
 ('he-mayim','palestinian','مَيّ','مي','מַיּ'),
 ('he-ani-rotze','msa','أُرِيدُ','أريد','אוּרִידֻ'),
 ('he-ani-rotze','palestinian','بِدِّي','بدي','בִּדִּי')
) AS v(entry_key,dialect,vocalized,search,transliteration)
JOIN dictionary_entries e ON e.entry_key=v.entry_key
ON CONFLICT (entry_id,dialect,arabic_vocalized) DO NOTHING;

INSERT INTO entry_sources (entry_id,source_id)
SELECT e.id,s.id
FROM dictionary_entries e CROSS JOIN dictionary_sources s
WHERE e.entry_key IN ('he-shalom','he-bayit','he-mayim','he-ani-rotze')
AND s.code='manual-demo'
ON CONFLICT (entry_id,source_id) DO NOTHING;

COMMIT;

-- Check after running: should show 4 demo entries and 8 Arabic forms.
SELECT
 (SELECT COUNT(*) FROM dictionary_entries) AS entries,
 (SELECT COUNT(*) FROM arabic_forms) AS arabic_forms,
 (SELECT COUNT(*) FROM dictionary_sources) AS sources;
